[package]
name = "aws-iot-device-sdk"
version = "0.0.3"
authors = ["awsa2ron <kaixu@amazon.com>"]
edition = "2021"
description = "aws iot device sdk in rust (unofficial)"
license = "MIT"

[dependencies]
arrayvec = { version = "0.7", default-features = false }
rand = "0.8.5"

[features]
std = []
